FROM nginx:alpine

# Копируем конфиг nginx
COPY nginx.conf /etc/nginx/nginx.conf

# Проверяем конфиг
RUN nginx -t

# Создаем директории для логов
RUN mkdir -p /var/log/nginx && \
    chmod 755 /var/log/nginx

# Открываем порты
EXPOSE 80

# Команда запуска
CMD ["nginx", "-g", "daemon off;"]
