events {
    worker_connections 1024;
}

http {
    server {
        listen 80;
        
        location / {
            proxy_pass http://vulnerable-app:5012;
            proxy_set_header Host $host;
        }
        
        location /static/ {
            alias /app/static/;
        }
        
        location /uploads/ {
            alias /app/uploads/;
        }
    }
}
